Car 44 add patient details columns for completing profile
DoubleHaoDev/carefusion-schema pull request #14
Opened 2024-08-31 04:23 UTC by Maxine311

我有先增加patients的欄位
不過我在寫的時候有個問題
就是每個這樣增加的欄位都一定要寫roolback嗎？
然後再notion上identification_type varchar [note: "Id, drivers licenses, passport"]
後面有特別寫note這個只是提醒的意思嗎？
還是需要放上去呢？

2024-08-31 04:54 UTC, DoubleHaoDev commented
> 我有先增加patients的欄位 不過我在寫的時候有個問題 就是每個這樣增加的欄位都一定要寫roolback嗎？ 然後再notion上identification_type varchar [note: "Id, drivers licenses, passport"] 後面有特別寫note這個只是提醒的意思嗎？ 還是需要放上去呢？

Liquibase 要不要寫rollback主要指令有沒有支援auto rollback.可以到Liquibase官方的文件看各種指令有沒有支援
比方說addColumn這個指令 到他addColumn的文件https://docs.liquibase.com/change-types/add-column.html 拉到最下面 可以看到postgresql有支援auto rollback就代表不用寫rollback. 如果沒有支援就必須寫rollback
例如 drop column就沒有支援 https://docs.liquibase.com/change-types/drop-column.html#xml_example
這時候就要自己寫rollback要做什麼事

[note: "Id, drivers licenses, passport"]就只是註記這裡面只會裝這三個值而已 等到到時候你改到後端程式的時候我在教你創enum規定identification_type column只能放這三種 string

2024-08-31 05:10 UTC, DoubleHaoDev requested changes
PR title 格式 [CAR-44] XXXXXX 我先幫你改掉了~

2024-08-31 05:10 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
我後來想一想,把first_name跟last_name 改到users table了 這樣就不用first_name & last_name都出現在 patients table跟physicians table. 你覺得如何？

2024-08-31 05:10 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      <column name="gender" type="varchar(150)">
gender 只有 male, female, 跟 others. 這樣應該varchar 10就夠了
```suggestion
      <column name="gender" type="varchar(10)">
```

2024-08-31 05:10 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      <column name="occupation" type="varchar(150)">
職位通常應該也不會太長,我覺得可以設定在30~50應該就足夠. 有些人可能沒工作 這欄可以考慮改成可以null,
或是沒工作就輸入待業之類的. 你覺得哪種比較好呢?

2024-08-31 05:10 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
這幾欄可以設定 defaultValueComputed="false" 讓預設值設為false

`<column name="privacy_concent" type="boolean" defaultValueComputed="false" >`

2024-08-31 05:10 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
這邊這個user_id 是連到users table的foreign key. 在columns加完後需要加上foreign key constraint.
可以參考這裡https://github.com/DoubleHaoDev/carefusion-schema/blob/master/schema/db-changelog.xml#L357-L365

2024-08-31 17:52 UTC, Maxine311 commented on schema/db-changelog.xml
> +      </column>
可以！
這樣是指first_name跟last_name只會出現在users table摟？

2024-08-31 17:53 UTC, Maxine311 commented on schema/db-changelog.xml
> +      <column name="occupation" type="varchar(150)">
我是覺得這個可以是null

2024-08-31 18:38 UTC, Maxine311 commented
> >> 我有先增加patients的欄位 不過我在寫的時候有個問題 就是每個這樣增加的欄位都一定要寫roolback嗎？ 然後再notion上identification_type varchar [note: "Id, drivers licenses, passport"] 後面有特別寫note這個只是提醒的意思嗎？ 還是需要放上去呢？
>> 
>> Liquibase 要不要寫rollback主要指令有沒有支援auto rollback.可以到Liquibase官方的文件看各種指令有沒有支援 比方說addColumn這個指令 到他addColumn的文件https://docs.liquibase.com/change-types/add-column.html 拉到最下面 可以看到postgresql有支援auto rollback就代表不用寫rollback. 如果沒有支援就必須寫rollback 例如 drop column就沒有支援 https://docs.liquibase.com/change-types/drop-column.html#xml_example 這時候就要自己寫rollback要做什麼事
>>
>> [note: "Id, drivers licenses, passport"]就只是註記這裡面只會裝這三個值而已 等到到時候你改到後端程式的時候我在教你創enum規定identification_type column只能放這三種 string
>>
>喔喔喔！我是指說在這個table上我有沒有需要加上rollback這件事，因為我是想說這是增加欄位應該還不用加上rollback，還是你會建議都加上去呢？

2024-08-31 19:03 UTC, Maxine311 commented on schema/db-changelog.xml
> +      <column name="uuid" type="UUID" defaultValueComputed="gen_random_uuid()">
想請問一下用uuid的原因是什麼呢？

2024-09-01 02:44 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
沒錯! 這樣不管是醫生還是病人登入的時候都可以從users table拿到名字.之前那樣設計還要從users分別連到 pateints跟physicians table才能拿到名字 算設計不良

2024-09-01 03:40 UTC, DoubleHaoDev requested changes

2024-09-01 03:40 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +  <changeSet id="CAR-44" author="Maxine Wu">
同一個ticket裡的東西都寫在同一個changeset裡面就可以～

2024-09-01 03:40 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      <column name="uuid" type="UUID" defaultValueComputed="gen_random_uuid()">
用uuid可以一定程度上防止int類型的id衝突的可能性,比方說雖然機會不大,但如果id 1的東西被刪除後你又insert新的 id1近來 就會產生不同時期同樣都是id 1但是指向不同的東西

2024-09-01 03:40 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +  <changeSet id="CAR-63" author="Andy Chang">
這個changeset加的地方錯了~ 這樣CAR-63出現兩次
`<changeSet id="CAR-44" author="Maxine Wu">`
應該要在CAR-63 的 `</changeSet>`以後

2024-09-01 03:40 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +    <createTable tableName="allergies">
allergies table 的建立必須要移到上面那些addForeignKeyConstraint之前
因為沒有allergies table的話FK會建不起來

2024-09-01 06:52 UTC, Maxine311 commented on schema/db-changelog.xml
> +  <changeSet id="CAR-63" author="Andy Chang">
啊！
不好意思這段是我昨天跑的時候發現我之前merge的時候好像不小心刪到這段
所以才補加上去

2024-09-01 06:53 UTC, Maxine311 commented on schema/db-changelog.xml
> +  <changeSet id="CAR-44" author="Maxine Wu">
好的
我把它全部移上去到CAR-44的地方

2024-09-01 06:53 UTC, Maxine311 commented on schema/db-changelog.xml
> +    <createTable tableName="allergies">
好的
我把它移到patient_allergies前面

2024-09-01 07:31 UTC, Maxine311 commented on schema/db-changelog.xml
> +      <column name="uuid" type="UUID" defaultValueComputed="gen_random_uuid()">
喔喔喔
了解～

2024-09-01 07:33 UTC, Maxine311 commented on schema/db-changelog.xml
> +    <createTable tableName="medications">
medication這個應該是藥物吧？
有沒有需要增加適應症和副作用的欄位呢？

2024-09-01 07:38 UTC, Maxine311 commented on schema/db-changelog.xml
> +    <addForeignKeyConstraint
這裡我想詢問一下identification_documents這個table的id
是可以reference到別的table的嗎?
因為我想說id這個欄位好像比較偏向屬於自己的

2024-09-01 18:14 UTC, DoubleHaoDev requested changes

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +    <addForeignKeyConstraint
這個table的id是用來連回patients table的 identification_document_id用的
之後用戶上傳身分證,護照等檔案會儲存在dentification_documents table

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +    <createTable tableName="medications">
我覺得可以加,不過一開始我怕會太過複雜
因為適應症跟副作用應該不會是單一的這樣又會需要開適應症跟副作用table再建立many to many relationship.
我會建議我們先把這個記起來,之後再加.
你覺得如何？

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
```suggestion
      <column name="privacy_concent" type="boolean" defaultValueComputed="false">
        <constraints nullable="false"/>
      </column>
```
這個欄位重複了~

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +        <constraints nullable="false" primaryKeyName="medications_pkey"/>
這裡漏了 `primaryKey="true"`
```suggestion
        <constraints nullable="false" primaryKeyName="medications_pkey" primaryKey="true"/>
```

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +        <constraints nullable="false" primaryKeyName="identification_documents_pkey"/>
這裡少了 `primaryKey="true"`
```suggestion
        <constraints nullable="false" primaryKeyName="identification_documents_pkey" primaryKey="true"/>
```

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +            referencedColumnNames="identification_document_id"
再看了一下設計 發現我patients table設計有錯誤
patients table 不需要 identification_document_id column
只需要靠這裡的FK就可以連結上了
```suggestion
            referencedColumnNames="id"
```

2024-09-01 18:14 UTC, DoubleHaoDev commented on schema/db-changelog.xml
> +      </column>
這裡沒設計好,這個欄位不需要了
```suggestion

```

2024-09-01 18:16 UTC, DoubleHaoDev commented
看起來 `<changeSet id="CAR-44" author="Maxine Wu"> `把 `<changeSet id="CAR-63" author="Andy Chang">` 再麻煩你改一下感謝

2024-09-02 01:40 UTC, Maxine311 commented on schema/db-changelog.xml
> +    <createTable tableName="medications">
好呀

2024-09-02 01:42 UTC, Maxine311 commented on schema/db-changelog.xml
> +    <addForeignKeyConstraint
喔喔喔
了解
只是我想說是不是會有需要再開另一個欄位叫identification_document_id是連到patients table

2024-09-02 02:04 UTC, Maxine311 commented
`<changeSet id="CAR-44" author="Maxine Wu">` 把 `<changeSet id="CAR-63" author="Andy Chang">`這個截斷的部分我有補齊了
抱歉

2024-09-02 04:16 UTC, DoubleHaoDev approved these changes
LGTM!

2024-09-02 04:16 UTC, merged